services:
  - type: web
    name: stock-trader-demo-backend
    env: docker
    rootDir: backend-api
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: development
      - key: DEMO_MODE
        value: true
      - key: OTP_DEBUG_MODE
        value: true
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://web-ruddy-eight-73.vercel.app
      - key: ALLOWED_ORIGINS
        value: https://web-ruddy-eight-73.vercel.app
      - key: DATABASE_URL
        sync: false
